name: Clifford Fajardo
description: "Software engineer, Sharing Ideas, Open Source"
meta_description: "blogging about web development, javascript, github, node, html, css, sass, scss and much more"

aboutPage: true
gems: [jekyll-paginate]
markdown: redcarpet
highlighter: pygments

paginate: 20
paginate_path: "page:num"
baseurl: /
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-41444051-2'
disqus: true
disqus_shortname: 'cliffordfajardo'

# Details for the RSS feed generator
url:            'archive/'
author:         'Clifford Fajardo'
authorTwitter:  'cliffordfajard0'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
